# Generated by Django 6.0.3 on 2026-03-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
