# Generated by Django 6.0.3 on 2026-03-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_asset_symbol_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='buy_price',
            new_name='avg_price',
        ),
    ]
